---
version: '3.6'
services:
    nginx:
        build:
            context: .
            target: azuriom-nginx
        restart: always
        env_file: .env
        ports:
            - "${PORT-80}:80"
    php-fpm:
        build:
            context: .
            target: azuriom-php
        restart: always
        env_file: .env
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=database
            - DB_PORT=5432
            - DB_DATABASE=azuriom
            - DB_USERNAME=azuriom
            - DB_PASSWORD=truc

    database:
        image: 'postgres:12'
        restart: always
        volumes:
            - pgsql-data:/var/lib/postgresql/data
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=azuriom
            - POSTGRES_USER=azuriom
            - POSTGRES_PASSWORD=truc
volumes:
    pgsql-data:
